name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
    - name: Build
      run: cargo build --verbose --release
    - name: Build Deb package
      cmd: cargo deb --target=x86_64-unknown-linux-musl
    
